# Generated by Django 5.1.4 on 2024-12-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerente',
            name='cpf',
            field=models.BigIntegerField(),
        ),
    ]
