# Generated by Django 5.1.4 on 2024-12-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0002_alter_gerente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.BigIntegerField(),
        ),
    ]
