# Generated by Django 5.1.4 on 2024-12-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0004_remove_gerente_id_remove_usuario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerente',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
