# Generated by Django 5.1.4 on 2025-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0005_alter_gerente_cpf_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='log',
            field=models.BooleanField(default=False),
        ),
    ]
