# Generated by Django 5.1.4 on 2025-02-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0006_usuario_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErroDetectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField()),
                ('linha', models.IntegerField(choices=[('Linha 1', 0), ('Linha 2', 1), ('Linha 3', 2)])),
                ('tipo_maquina', models.IntegerField(choices=[('Preta', 0), ('Branca', 1)])),
                ('imagem', models.FilePathField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Funcionario',
        ),
    ]
