# Generated by Django 5.1.4 on 2025-02-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0007_errodetectado_rename_usuario_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errodetectado',
            name='linha',
            field=models.IntegerField(choices=[(0, 'Linha 1'), (1, 'Linha 2'), (2, 'Linha 3')]),
        ),
        migrations.AlterField(
            model_name='errodetectado',
            name='tipo_maquina',
            field=models.IntegerField(choices=[(0, 'Preta'), (1, 'Branca')]),
        ),
    ]
