# Generated by Django 5.1.4 on 2025-02-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0008_alter_errodetectado_linha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errodetectado',
            name='momento',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
