# Generated by Django 5.1.4 on 2025-02-12 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0012_alter_errodetectado_momento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errodetectado',
            name='momento',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 17, 36, 59, 229637, tzinfo=datetime.timezone.utc)),
        ),
    ]
