# Generated by Django 5.1.4 on 2025-02-12 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0014_alter_errodetectado_momento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errodetectado',
            old_name='tipo_maquina',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='errodetectado',
            name='momento',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 17, 39, 30, 942491, tzinfo=datetime.timezone.utc)),
        ),
    ]
