# Generated by Django 5.1.4 on 2025-02-13 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0015_rename_tipo_maquina_errodetectado_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errodetectado',
            name='imagem',
            field=models.FilePathField(path='images'),
        ),
        migrations.AlterField(
            model_name='errodetectado',
            name='momento',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 13, 15, 32, 39, 892102, tzinfo=datetime.timezone.utc)),
        ),
    ]
