# Generated by Django 5.1.4 on 2025-02-14 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0020_alter_errodetectado_momento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errodetectado',
            name='imagem',
            field=models.FilePathField(path='/images'),
        ),
        migrations.AlterField(
            model_name='errodetectado',
            name='momento',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 14, 3, 30, 51, 157517, tzinfo=datetime.timezone.utc)),
        ),
    ]
