# Generated by Django 5.1.4 on 2025-02-14 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0021_alter_errodetectado_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errodetectado',
            name='imagem',
            field=models.FilePathField(path='C:\\Users\\pedroituassu\\Documents\\UEA\\Callidus\\Detectoy\\detectoy\\detectoyBackEnd\\Detectoy\\images'),
        ),
        migrations.AlterField(
            model_name='errodetectado',
            name='momento',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 14, 3, 32, 34, 749923, tzinfo=datetime.timezone.utc)),
        ),
    ]
