# Generated by Django 5.1.4 on 2025-03-09 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0024_alter_errodetectado_momento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errodetectado',
            name='imagem',
            field=models.FilePathField(path='/home/pedroituassu/projects/Detectoy/detectoyBackEnd/Detectoy/images'),
        ),
        migrations.AlterField(
            model_name='errodetectado',
            name='momento',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 9, 4, 0, 7, 112795, tzinfo=datetime.timezone.utc)),
        ),
    ]
