# Generated by Django 5.1.4 on 2025-03-19 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0026_erro_delete_errodetectado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erro',
            name='linha',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='erro',
            name='momento',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 5, 4, 20, 194338, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='erro',
            name='tipo',
            field=models.IntegerField(),
        ),
    ]
