# Generated by Django 5.1.4 on 2025-03-19 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0027_alter_erro_linha_alter_erro_momento_alter_erro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erro',
            name='momento',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 5, 16, 3, 771361, tzinfo=datetime.timezone.utc)),
        ),
    ]
