# Generated by Django 5.1.4 on 2025-03-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detectoy', '0029_alter_erro_momento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erro',
            name='imagem',
            field=models.FilePathField(path='C:\\Users\\User\\Desktop\\Detectoy\\detectoyBackEnd\\Detectoy\\images'),
        ),
    ]
